OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Haha…  Did my brother send you to find\n"
	.string "me?  You got it!  I'm JOVI!\p"
	.string "Nice to meetcha.  Try to pay attention,\n"
	.string "m'kay?  MICHAEL wanted me to give you\l"
	.string "something, but that's boring, so we'll\l"
	.string "play a game.  I want to see POKéDEX\l"
	.string "data on 5 POKéMON!  Can you do that?$"

